# Generated by Django 5.1.1 on 2024-10-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
